### ISSUE TITLE
Cleanup repository

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/workshop#111]
There is this proposal to clean up the repository, that was approved:
https://lists.osgeo.org/pipermail/pgrouting-dev/2020-December/002160.html

tasks: 
- [x] `master` move to `main`
- [x] general-develop move to `develop`
- [x] delete `foss4gBucharest` the [tag](https://github.com/pgRouting/workshop/releases/tag/v2.6.0) has been [published](https://workshop.pgrouting.org/2.6/en/index.html)
- [x] delete `foss4gBoston` the [tag](https://github.com/pgRouting/workshop/releases/tag/v2.4.11) has been [published](https://workshop.pgrouting.org/2.4.11/en/index.html)
- [x] delete branch `develop/foss4g2016` the [tag](https://github.com/pgRouting/workshop/releases/tag/v2.2.10) has been [published](https://workshop.pgrouting.org/2.2.10/en/index.html)
- [x]  delete branch `foss4g2014` the [tag](https://github.com/pgRouting/workshop/releases/tag/2.0.6) has been [published](https://workshop.pgrouting.org/2.0.6/en/index.html)
- [x] delete branch `foss4g2013` the [tag](https://github.com/pgRouting/workshop/releases/tag/2.0.2) has been [published](https://workshop.pgrouting.org/2.0.2/en/index.html)
- [x] foss4g2011 the [tag](https://github.com/pgRouting/workshop/releases/tag/v0.6.1) has been [published](https://workshop.pgrouting.org/0.6.1/en/index.html)
- [x] create tag for `foss4gOkayama` 
  - [x] Can it be published?
  - [x] delete branch
- [x] delete unused currently `testlang` 
- [x] branch `develop/hokkaido`
  - [x] Can it be published?
  - [x] Create tag
  - [x] delete branch
- [x] branch `ja_20141110`
  - [x] Can it be published?
  - [x] Create no tag
  - [x] delete branch
- [x] agit2014
  - [x] Can it be published? No
  - [x] Create tag
  - [x] delete branch
- [x] create tag for `pgr-1.x`
   - [x] Do we care to publish it? No
     - [x] Create tag
   - [x] delete branch

**Comment by sanak** [comment]
@cvvergara
Thanks for cleaning up work!

About `foss4gOkayama` branch, the following version is published (as English).
- https://workshop.pgrouting.org/2.5/en/index.html (session introduction is here: https://www.osgeo.jp/events/foss4g-2018/foss4g-2018-okayama/foss4g-2018-okayama-handson#pgRouting)

About `ja_20141110`, it is just backup of my local environment and was not published anywhere, so you can delete it (without creating tag).

About `develop/hokkaido`, I think that it is published by @dkastl at FOSS4G 2016 Hokkaido (Here is event introduction: https://foss4g2016hkdhanson2.peatix.com/?lang=ja)

**Comment by cvvergara** [comment]
master is now named main

If you have a local clone, you can update it by running:
git branch -m master main
git fetch origin
git branch -u origin/main main

**Comment by omshinde** [comment]
`general-develop` is now renamed `develop`

If you have a local clone, you can update it by running:
```
git branch -m general-develop develop
git fetch origin
git branch -u origin/develop develop
```
