### ISSUE TITLE
[FOSS4G 2021 BA] Automatically update the conf.py for cmake workshop

### ISSUE THREAD

**Issue by omshinde** [pgRouting/workshop#112]
**Problem**
For the automated workshop, the [conf.py](https://github.com/pgRouting/workshop/blob/develop/docs/conf.py#L46) parameters are not updating automatically.

The following needs to be updated:
- [Workshop title](https://github.com/pgRouting/workshop/blob/develop/docs/conf.py#L46)
- [Copyright year](https://github.com/pgRouting/workshop/blob/develop/docs/conf.py#L47)
- [Version](https://github.com/pgRouting/workshop/blob/develop/docs/conf.py#L54)
- [Full version](https://github.com/pgRouting/workshop/blob/develop/docs/conf.py#L56)
- [HTML Title](https://github.com/pgRouting/workshop/blob/develop/docs/conf.py#L56)
- [HTML Short title](https://github.com/pgRouting/workshop/blob/develop/docs/conf.py#L129)

**Comment by cvvergara** [comment]
Related to #104

**Comment by cvvergara** [comment]
with PR #114
