### ISSUE TITLE
Intent of Application of Veenit Kumar

### ISSUE THREAD

**Issue by veenits123** [pgRouting/workshop#116]
- [x] Intent of application 
- [ ] Experience with GitHub & Git
- [ ] Build locally the workshop
- [ ] Get familiar with the workshop
- [ ] Get familiar with Sphinx

**Comment by cvvergara** [comment]
@Veenits123 
Please leave a paragraph about yourself
and dont forget to put the links to the work done, otherwise I can not check the boxes
