### ISSUE TITLE
Chapter 6 problem structures

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/workshop#137]
- [x] Structure of problems to be the same as described in #136

**Comment by omshinde** [comment]
- [ ] titles: First letter upper case, no period at the end
- [ ] Update signature: `pgr_dijkstra(Edges SQL, Combinations SQL [, directed])`
- [ ] Follow the structure of a problem on all problems where applicable

# structure of an exercise

## Exercise N: Short description
**Problem:**
Walking from **Plaza Intendente Alvear** to the **Facultad de Derecho**

(image)

**Soltution**
* bullet
* bullet
```
code
```
Exercise N query results
