### ISSUE TITLE
Intent of application

### ISSUE THREAD

**Issue by rapoma** [pgRouting/workshop#149]
- [x] Intent of application 
- [x] Experience with GitHub & Git
- [x] Build locally the workshop
- [ ] Get familiar with the workshop
- [ ] Get familiar with Sphinx

**Comment by rapoma** [comment]
[PR] https://github.com/pgRouting/workshop/pull/150
[Issue] https://github.com/rapoma/workshop/issues/1

**Comment by rapoma** [comment]
https://github.com/rapoma/workshop/issues/2

**Comment by cvvergara** [comment]
Welcome @rapoma 
Please put on a comment a small paragraph about yourself

**Comment by rapoma** [comment]
I graduated from Mathematics. I worked in a multidisciplinary Lab  (FULL- Politecnico di Torino, ITALY) as an assistant researcher (Computer vision project using machine learning approach (application and research), develop software such as plugin in QGIS (https://github.com/AndLouis/adrem)).  Further information could be found in https://www.nantenaina.xyz/ .

**Comment by cvvergara** [comment]
@rapoma I wonder how you are doing? are you stuck?
