### ISSUE TITLE
Florence

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/workshop#209]
Tasks:

- [x] get data BBOX
- [x] get osm_id of special locations
- [x] get names of special locations
- [x] bbox of small net
- [x] lat lon of 2 locations not on roads
- [x] create necessary images

**Comment by cvvergara** [comment]
BBOX:
             43.7950
11.2028              11.2702
             43.7658

**Comment by cvvergara** [comment]
Created a PR to the OSGeoLive project for about that area
https://github.com/OSGeo/OSGeoLive/pull/318

**Comment by omshinde** [comment]
Potential Special locations: 
1. Railway Station - [Stazione di Santa Maria Novella](https://www.openstreetmap.org/relation/3324492)
2. Cathedral - [Florence Cathedral](https://www.openstreetmap.org/search?query=Florence%20Cathedral#map=19/43.77302/11.25650)
3. Central Market - [Mercato Centrale](https://www.openstreetmap.org/node/5188361676)
4. Florence Airport - [Aeroporto Firenze Amerigo Vespucci](https://www.openstreetmap.org/relation/1788587)
5. Workshop Venue - [Università degli Studi di Firenze](https://www.openstreetmap.org/node/7288512936)
6. Conference Venue - [Palazzo dei Congressi](https://www.openstreetmap.org/node/5058828321#map=18/43.77830/11.24980)
7. Hotel - [Hotel Albani](https://www.openstreetmap.org/node/938199512#map=19/43.77690/11.25032)

**Comment by cvvergara** [comment]
Venue [Palazzo dei Congressi](https://www.openstreetmap.org/node/5020458299) : 5020458299

**Comment by cvvergara** [comment]
Workshop venue [Learning center morgagni](https://www.openstreetmap.org/node/5221155713) 5221155713

**Comment by cvvergara** [comment]
Venue [Palazzo dei Congressi](https://www.openstreetmap.org/node/5020458299) : 5020458299
Hotel - [Hotel Albani](https://www.openstreetmap.org/node/938199512#map=19/43.77690/11.25032) - 6483155124
Railway Station - [Stazione di Santa Maria Novella](https://www.openstreetmap.org/node/1835203780#map=16/43.7776/11.2474) - 2531656518
Cathedral - [Florence Cathedral](https://www.openstreetmap.org/search?query=Florence%20Cathedral#map=19/43.77302/11.25650) - 1798374718
Central Market - [Mercato Centrale](https://www.openstreetmap.org/node/5188361676) - 266939565

The workshop is toooooo far
