### ISSUE TITLE
introduction.html

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/workshop#47]
Grammar and spelling

**Comment by cvvergara** [comment]
tools for shortest path search as extension of PostgreSQL and PostGIS.
change to
 tools for shortest path search as an extension of PostgreSQL and PostGIS.

**Comment by cvvergara** [comment]
List starts with capital letter, but lines end with comma
* Installing pgRouting,
* Creating a routing topology,

**Comment by cvvergara** [comment]
(Version 12.0)  change to (Version 13.0)

**Comment by cvvergara** [comment]
Do:
Start with Capital letter and end lines with period

**Comment by omshinde** [comment]
Update Abstract: Grammar

pgRouting adds routing functionality to PostGIS. This introductory workshop will show you how. Providing practical examples using OpenStreetMap road network data. Covering from how to prepare the data, make routing queries, write a custom 'plpgsql' functions up to draw your route in a web-mapping application. In other words, integrating pgRouting with other FOSS4G tools.

Change to 

pgRouting adds routing functionality to PostGIS. This introductory workshop will demostrate it by providing practical examples using OpenStreetMap road network data. It will be covering topics from how to prepare the data, make routing queries, write a custom 'plpgsql' functions up to draw your route in a web-mapping application. In other words, integrating pgRouting with other FOSS4G tools.
