### ISSUE TITLE
about.html

### ISSUE THREAD

**Issue by MarPetra** [pgRouting/workshop#48]
Gramar and Spelling

**Comment by MarPetra** [comment]
The text box is too large and I think it doesn't look nice. Will we keep it?

**Comment by MarPetra** [comment]
Some of the pgRouting library core features are:
- Dijkstra Algorithm
- Johnson’s Algorithm
- Floyd-Warshall Algorithm

links send us to wikipedia, some lines do not have a link.
Shall we use pgRouting documemntation links instead?

**Comment by MarPetra** [comment]
> and maintained by Georepublic, iMaptools and a broad user community.

missing include the company Paragon Corporation.
Is the list complete?

**Comment by MarPetra** [comment]
> pgRouting is an OSGeo Community Projects project of the OSGeo Foundation and included on OSGeoLive.

Links are strange

**Comment by MarPetra** [comment]
> “OpenStreetMap is a project aimed squarely at creating and providing free geographic data such as street maps to anyone who wants them. The project was started because most maps you think of as free actually have legal or technical restrictions on their use, holding back people from using them in creative, productive or unexpected ways.”

The quote does not exist on the link anymore

**Comment by MarPetra** [comment]
Inconsistence links on the logos

**Comment by omshinde** [comment]
Grammar in sentence structure:

This workshop uses several FOSS4G tools. Most of FOSS4G software is related to other open source projects and it would go too far to list them all here.

change to-

This workshop uses several FOSS4G (Free and Open Source Software for Geospatial) tools. Most of the FOSS4G tools are
related to other open-source software (OSS) projects and it would not be feasible to list all of them.

**Comment by omshinde** [comment]
#### Update "Pl/pgSQL" -> "PL/pgSQL" in Section 2.1: pgRouting Overview

Advantages of the database routing approach are:
- Data and attributes can be modified by many clients, like QGIS and uDig through JDBC, ODBC, or directly using Pl/pgSQL. The clients can either be PCs or mobile devices.

change to-

Advantages of the database routing approach are:
- Data and attributes can be modified by many clients, like QGIS and uDig through JDBC, ODBC, or directly using **PL/pgSQL**. The clients can either be PCs or mobile devices.

**Comment by omshinde** [comment]
> Some of the pgRouting library core features are:
> 
> * Dijkstra Algorithm
> * Johnson’s Algorithm
> * Floyd-Warshall Algorithm
> 
> links send us to wikipedia, some lines do not have a link.
> Shall we use pgRouting documemntation links instead?

The wikipedia link is not available for Driving distance algorithm as it can be defined under Dijkstra Algorithm Family. Source: [pgRouting Docs Dijkstra Family](https://docs.pgrouting.org/latest/en/dijkstra-family.html). The Dijkstra algorithm is already present in the list so we can replace Driving Distance option with other examples. Maybe Components family of functions. Source: [pgRouting Docs Components Family](https://docs.pgrouting.org/latest/en/components-family.html). We also have a [wiki](https://en.wikipedia.org/wiki/Component_(graph_theory)) page explaining the same.

Please suggest.

**Comment by omshinde** [comment]
#### Update Nested Bullet list in Section 2.1: pgRouting Overview

Some of the pgRouting library core features are:

- Dijkstra Algorithm
- Johnson’s Algorithm
- Floyd-Warshall Algorithm
- A* Algorithm
- Bi-directional Algorithms * Bi-directional Dijkstra * Bi-directional A*

change to -

Some of the pgRouting library core features are:

- Dijkstra Algorithm
- Johnson’s Algorithm
- Floyd-Warshall Algorithm
- A* Algorithm
- **Bi-directional Algorithms** 
   - Bi-directional Dijkstra 
   - Bi-directional A*

**Comment by omshinde** [comment]
> > and maintained by Georepublic, iMaptools and a broad user community.
> 
> missing Paragon Corporation.
> Is the list complete?

Is there a list available online which can be referred to update the workshop?
Also, the link to [iMaptools](http://www.imaptools.com/) is not redirecting to the proper website or their website is under maintainence. Please verify.

**Comment by omshinde** [comment]
> > “OpenStreetMap is a project aimed squarely at creating and providing free geographic data such as street maps to anyone who wants them. The project was started because most maps you think of as free actually have legal or technical restrictions on their use, holding back people from using them in creative, productive or unexpected ways.”
> 
> The quote does not exist on the link anymore

Correct. We can change this by updated quote.

#### OpenStreetMap Overview - Section 2.3

"OpenStreetMap is a project aimed squarely at creating and providing free geographic data such as street maps to anyone who wants them. The project was started because most maps you think of as free actually have legal or technical restrictions on their use, holding back people from using them in creative, productive or unexpected ways."

change to-

"OpenStreetMap (OSM) is dedicated to creating and providing geographic data, such as street maps, worldwide, for free.

Most maps considered "free" actually have legal or technical restrictions on their use. These restrictions hold back anyone from using them in creative, productive or unexpected ways, and make every map a silo of data and effort."

Source: [https://wiki.openstreetmap.org/wiki/Portal:Press](https://wiki.openstreetmap.org/wiki/Portal:Press)

**Comment by omshinde** [comment]
> Inconsistence links on the logos

#### Updated links

1. OpenStreetMap Logo
   [https://live.osgeo.org/en/overview/osm_dataset_overview.html](https://live.osgeo.org/en/overview/osm_dataset_overview.html) -> [http://www.openstreetmap.org/](http://www.openstreetmap.org/)

   Added [https://live.osgeo.org/en/overview/osm_dataset_overview.html](https://live.osgeo.org/en/overview/osm_dataset_overview.html) in the bottom with OSGeoLive tag.

**Comment by omshinde** [comment]
> > pgRouting is an OSGeo Community Projects project of the OSGeo Foundation and included on OSGeoLive.
> 
> Links are strange

#### Update link for the OSGeo foundation

[https://osgeo.org/](https://osgeo.org/) -> [https://www.osgeo.org/](https://www.osgeo.org/)

Ideally, both of them should redirect to same page but it seems that [https://osgeo.org/](https://osgeo.org/) redirects to [https://www.osgeo.org/community/getting-started-osgeo/osgeo_userid/](https://www.osgeo.org/community/getting-started-osgeo/osgeo_userid/). Hence, strange behaviour.

**Comment by cvvergara** [comment]
@omshinde 
reported
https://trac.osgeo.org/osgeo/ticket/2395#ticket
