### ISSUE TITLE
installation.html

### ISSUE THREAD

**Issue by MarPetra** [pgRouting/workshop#49]
Grammar and spelling

**Comment by MarPetra** [comment]
> All required tools are available on OSGeo Live.

Change to OSGeoLive

**Comment by MarPetra** [comment]
> replace ‘<mydist>’ with ‘artful’, ‘zesty’, ‘yakkety’, ‘xenial’, ‘trusty’, ‘stretch’, ‘jessie’, or ‘wheezy’

Is the list correct?

**Comment by MarPetra** [comment]
> 3.1.2. Download OSGeoLive 12.0

It must be 13.0

**Comment by MarPetra** [comment]
missing contents section

**Comment by MarPetra** [comment]
virtualbox images are probably outdated

**Comment by MarPetra** [comment]
> 4.2.2.1. Option 1) When using OSGeo Live
OSGeo Live comes with osm data from the city of Bucharesti

it should say Bucharest

**Comment by MarPetra** [comment]
> More information how to download OpenStreetMap information can be found in http://wiki.openstreetmap.org/wiki/Downloading_data

And it should say "More information about how to..."
Dead link :(

**Comment by pranayteaches** [comment]
> virtualbox images are probably outdated

have created some new ones
![downloadOSGeoLive](https://user-images.githubusercontent.com/35572191/71376665-421c1b00-25e8-11ea-80aa-791fcc82d784.PNG)
![install-disk](https://user-images.githubusercontent.com/35572191/71376667-42b4b180-25e8-11ea-96e0-77b61b430398.PNG)
![install-final](https://user-images.githubusercontent.com/35572191/71376670-42b4b180-25e8-11ea-8981-f28d56ff9206.PNG)
![install-general](https://user-images.githubusercontent.com/35572191/71376671-434d4800-25e8-11ea-907d-0a0450f41cf7.PNG)
![install-memory](https://user-images.githubusercontent.com/35572191/71376672-434d4800-25e8-11ea-90aa-c8c2f2a5e7c7.PNG)
![install-name](https://user-images.githubusercontent.com/35572191/71376673-43e5de80-25e8-11ea-813b-ac45ce3e8a0a.PNG)
![install-vm](https://user-images.githubusercontent.com/35572191/71376674-43e5de80-25e8-11ea-8f4e-ab7626d7e073.PNG)
![install-welcome](https://user-images.githubusercontent.com/35572191/71376676-447e7500-25e8-11ea-9944-300837ea8389.PNG)

**Comment by pranayteaches** [comment]
all the above are captured today, with the latest version of Virtual manager and OSGeoLive(13)

**Comment by pranayteaches** [comment]
By The way hello myself Pranay, I am a participant in GCI and has taken OSGeo as the company and came to know about it through it.

**Comment by omshinde** [comment]
> virtualbox images are probably outdated

Addressed in #64
