### ISSUE TITLE
Errors while installing REQUIREMENTS.txt

### ISSUE THREAD

**Issue by omshinde** [pgRouting/workshop#51]
Encountered errors while installing requirements mentioned in REQUIREMENTS.txt

Command executed: 
```pip install -r REQUIREMENTS.txt```

Error Message:
``` error: invalid command 'bdist_wheel' ```

OS: Ubuntu 16.04
Python development Environment: Python 3

**Comment by pranayteaches** [comment]
Hello, @omshinde Here are some solutions of your problem
1. this is the easiest solution (most accurate one)
install wheel using ``` pip install wheel ``` and then try reinstalling it.
if this doesn't work then only try the others
2. try updating pip
``` pip install --upgrade pip ```
3. try updating setuptools 
``` sudo -H pip install setuptools --upgrade ```
4. try installing using ``` travis ``` instead of ``` sudo ```

**Comment by pranayteaches** [comment]
Most probably the first step shouldwork for you.

**Comment by pranayteaches** [comment]
Well if any further problem arises contact me.

**Comment by cvvergara** [comment]
@pranayteaches 
* (3) is not suitable.
Unfortunately for developers its not good to use sudo when using pip
https://askubuntu.com/questions/802544/is-sudo-pip-install-still-a-broken-practice
* (2) is not suitable.
Project packagers normally grab the requirements as they are without upgrading pip
that is not a solution for other OS like centos, fedora, etc.
We try to be as universal as possible

* (1) I need to try
* (4) I don't understand what you mean

**Comment by pranayteaches** [comment]
I told to try the first one as its most accurate

**Comment by pranayteaches** [comment]
I told to install wheel 
As this will probably solve the problem
And gave others as extras.

**Comment by cvvergara** [comment]
Looks like (1) works

**Comment by pranayteaches** [comment]
Oh well Great. If it really works and if it doesn't you may contact me anytime you want.
Will be happy to help you.

**Comment by cvvergara** [comment]
@pranayteaches 
you can make a PR that:
* in REQUIREMENTS.txt
  * adds `wheel`
  * leaves only `Sphinx`, `sphinx_bootstrap_theme`, `sphinx-intl` but instead of `==` use `>=` for the versions
* Modifies the README.md as this requirement is for translation handling
  * transifex-client==0.13.4

**Comment by pranayteaches** [comment]
hello @cvvergara what should I mention there

**Comment by pranayteaches** [comment]
Your points are good but I also want to add that Users may also solve it by ``` pip install wheel ```
could i add this
As it might be a good Idea

**Comment by pranayteaches** [comment]
mam could you guide me to create a pr
as I am able to but not sure is that the right way
1. what we have to compare

**Comment by omshinde** [comment]
I got it working by adding ```wheel``` to the **REQUIREMENTS.txt** file and executing `pip install -r REQUIREMENTS.txt --upgrade` for installation. 

Possible justification could be because of dependency issues between the new versions of `Sphinx`, `sphinx_bootstrap_theme` and `sphinx-intl`.

Screenshot of workshop image - ![pgRoutingWorkshop](https://user-images.githubusercontent.com/21292545/71449975-978a3080-277e-11ea-9657-3d865544a2ce.png)

@cvvergara , @pranayteaches : Please review it before making a PR.

**Comment by pranayteaches** [comment]
![IMG_20200121_225108](https://user-images.githubusercontent.com/35572191/72827590-15b7f500-3ca1-11ea-8a31-5d98013910cf.jpg)

**Comment by pranayteaches** [comment]
![IMG_20200122_220749](https://user-images.githubusercontent.com/35572191/72913964-f33ae000-3d63-11ea-9b49-1000cc3e7f28.jpg)

**Comment by cvvergara** [comment]
Travis is working now
