### ISSUE TITLE
prepare_data.html

### ISSUE THREAD

**Issue by omshinde** [pgRouting/workshop#54]
##### Common to all sections
1. OSGeo Live -> OSGeoLive

##### Section 4.1 - [Prepare the database](https://workshop.pgrouting.org/2.6/en/chapters/prepare_data.html#prepare-the-database)

1. "These requirements are met on OSGeoLive, then open a terminal window ctrl-alt-t and follow the instructions."
    change to ->
    "These requirements are met on OSGeoLive. **Once done,** open a terminal window **by pressing** ctrl-alt-t and follow the instructions."

2. Section 4.1.1: "configureation" -> "configuration"

##### Section 4.2 - [Get the workshop data](https://workshop.pgrouting.org/2.6/en/chapters/prepare_data.html#get-the-workshop-data)

1. Section 4.2.2.1: 
"Bucharesti" -> "Bucharest"

2. Section 4.2.2.3:
    - "Using this data in the workshop can generate variations on the results, due to changes since Jun-2017" -> "Using this data in the workshop can generate variations **in** the results, due to changes since Jun-2017."
    - "More information how to download OpenStreetMap information can be found in http://wiki.openstreetmap.org/wiki/Downloading_data" -> "More information about how to download OpenStreetMap **data** can be found in http://wiki.openstreetmap.org/wiki/Downloading_data"

**Comment by cvvergara** [comment]
Bucharesti is how the people in Bucharest write it
